export const SpanishSubRegions = {
  BARCELONA: { code: 'ES-B', description: 'Barcelona' },
  ALBACETE: { code: 'ES-AB', description: 'Albacete' },
  ALICANTE_ALACANT: { code: 'ES-A', description: 'Alicante/Alacant' },
  ALMERÍA: { code: 'ES-AL', description: 'Almería' },
  ARABA_ÁLAVA: { code: 'ES-VI', description: 'Araba/Álava' },
  ASTURIAS: { code: 'ES-O', description: 'Asturias' },
  ÁVILA: { code: 'ES-AV', description: 'Ávila' },
  BADAJOZ: { code: 'ES-BA', description: 'Badajoz' },
  CEUTA: { code: 'ES-CE', description: 'Ceuta' },
  MELILLA: { code: 'ES-ML', description: 'Melilla' },
  VALÈNCIA: { code: 'ES-V', description: 'València' },
  VALLADOLID: { code: 'ES-VA', description: 'Valladolid' },
  ZARAGOZA: { code: 'ES-Z', description: 'Zaragoza' },
  TARRAGONA: { code: 'ES-T', description: 'Tarragona' },
  TERUEL: { code: 'ES-TE', description: 'Teruel' },
  TOLEDO: { code: 'ES-TO', description: 'Toledo' },
  SEGOVIA: { code: 'ES-SG', description: 'Segovia' },
  SEVILLA: { code: 'ES-SE', description: 'Sevilla' },
  SORIA: { code: 'ES-SO', description: 'Soria' },
  SANTA_CRUZ_DE_TENERIFE: { code: 'ES-TF', description: 'Santa Cruz de Tenerife' },
  PONTEVEDRA: { code: 'ES-PO', description: 'Pontevedra' },
  SALAMANCA: { code: 'ES-SA', description: 'Salamanca' },
  LEÓN: { code: 'ES-LE', description: 'León' },
  LUGO: { code: 'ES-LU', description: 'Lugo' },
  LLEIDA: { code: 'ES-L', description: 'Lleida' },
  LA_RIOJA: { code: 'ES-LO', description: 'La Rioja' },
  LAS_PALMAS: { code: 'ES-GC', description: 'Las Palmas' },
  PALENCIA: { code: 'ES-P', description: 'Palencia' },
  OURENSE: { code: 'ES-OR', description: 'Ourense' },
  NAVARRA: { code: 'ES-NA', description: 'Navarra' },
  MURCIA: { code: 'ES-MU', description: 'Murcia' },
  ILLES_BALEARS: { code: 'ES-PM', description: 'Illes Balears' },
  BIZKAIA: { code: 'ES-BI', description: 'Bizkaia' },
  BURGOS: { code: 'ES-BU', description: 'Burgos' },
  CÁCERES: { code: 'ES-CC', description: 'Cáceres' },
  CÁDIZ: { code: 'ES-CA', description: 'Cádiz' },
  CANTABRIA: { code: 'ES-S', description: 'Cantabria' },
  CASTELLÓN: { code: 'ES-CS', description: 'Castellón' },
  CIUDAD_REAL: { code: 'ES-CR', description: 'Ciudad Real' },
  CÓRDOBA: { code: 'ES-CO', description: 'Córdoba' },
  A_CORUÑA: { code: 'ES-C', description: 'A Coruña' },
  CUENCA: { code: 'ES-CU', description: 'Cuenca' },
  GIPUZKOA: { code: 'ES-SS', description: 'Gipuzkoa' },
  GIRONA: { code: 'ES-GI', description: 'Girona' },
  GRANADA: { code: 'ES-GR', description: 'Granada' },
  GUADALAJARA: { code: 'ES-GU', description: 'Guadalajara' },
  HUELVA: { code: 'ES-H', description: 'Huelva' },
  HUESCA: { code: 'ES-HU', description: 'Huesca' },
  JAÉN: { code: 'ES-J', description: 'Jaén' },
  MADRID: { code: 'ES-M', description: 'Madrid' },
  MÁLAGA: { code: 'ES-MA', description: 'Málaga' },
  ZAMORA: { code: 'ES-ZA', description: 'Zamora' }
};

